### PR TITLE
Push to upstream of changes.

### PR DESCRIPTION
**Pull request by gwurster**
This patch contains a number of different features:

1. More comprehensive unit testing, in the tests directory.  The unit
   tests contain a large number of sample patches which exercise
   various conditions.  Some of these unit tests pass, while others
   fail and need fixes in the main application to properly deal with
   them.

2. Fixes for \n appearing in the source file, which was previously
   being changed into an actual newline and caused patches to fail to
   apply.

3. Not ignoring new lines when determining where to apply a patch,
   which was causing some patches that had already been applied to be
   applied again.

4. Cleaning up the command line output, including adding a -v option
   (to increase verbosity), adding a --dry-run option (which allows us
   to test without actually applying the patch), and
   indenting/applying horizontal lines to break up the sections
   properly.

5. Dealing with patch files which have different @@ context lines.

6. Detecting patches that git apply has skipped.

7. Attempting to apply patches when not sitting at the root of a GIT path.

8. Being able to run apply.py from an arbitrary directory.

### CODE REVIEW

**Comment by vikramsubramanian** [comment]
Hello everyone,

Firstly, my most sincere apologies for the very late processing of this PR. Secondly, WOW! The PR makes the tool a whole lot better in every way!

I went through the code and ran it. I really don’t have any major comments. Here are my observations-

1. Thank you for the make file. Build and running is much more intuitive + simple now. 
1. Thank you for cleaning up the code + error handling. It really needed it!
1. We were writing a lot of patches for the ‘\n’ case. From the cases I’ve run, it looks like your solution fixes it more robustly (and systematically) 
1. We could maybe consider adding more detail to the documentation and user instructions- Even I found it a little tricky to use the tool after so long! 
1. If your 8th point refers to being able to run the tool without apply.py being in a specific location, it works great! 
1. Your 7th point indicated that you only attempted to “apply patches when not sitting at the root of a GIT path”. I was not able to isolate the code that corresponds to that attempt. But the PR is so big, I could have easily missed it :) Maybe we could highlight this limitation in the documentation?
1. I found your test cases to be a masterclass- I actually learned a lot on how to test code. Thank you!
1. Could explaining the regex in scripts/patch_apply/patchParser.py help? Granted I have not worked with this kind of stuff much before but I didn’t really understand what was happening. 

I’d be more than happy to work on the documentation changes I mentioned above.

**Comment by gwurster** [comment]
With regards to #6 above, if GIT apply detects that, for a patch applying to dir/file.c, the actual root is path/dir/file.c (since we're currently sitting inside the path directory), it'll report it's finding against path/dir/file.c.  This caused a mismatch where we would look at the patch file, notice no error messages against dir/file.c from GIT, and assume the patch had been applied successfully (since the error message was against path/dir/file.c).  The fix is starting at https://github.com/gwurster/ApplyPlus/blob/master/scripts/patch_apply/apply.py#L19, with another comment at https://github.com/gwurster/ApplyPlus/blob/master/scripts/patch_apply/apply.py#L294.  The test code for the findGitPrefix function is https://github.com/gwurster/ApplyPlus/blob/master/tests/test_apply.py#L94.

With regards to #8, https://github.com/gwurster/ApplyPlus/blob/master/scripts/patch_apply/patchParser.py#L62 is the start of the regular expressions that I think you're referring to.  The @@....@@ lines for hunk location is described at https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html.  The 'from-file-line-numbers' and 'to-file-line-numbers' contain a 'start,count', but the count only exists if there is more than one line.  The previous string split call assumed all four numbers always existed and would raise an exception if the count was missing on either the from or to line numbers.  A test case which causes a missing count is either patching a file that was originally one line long, or removing from a file so that the end result is a file that is one line long.  It appears I missed adding a test case for those situations.

**Comment by vikramsubramanian** [comment]
Hi Glen,

I talked to Prof. Mei and he asked me to take a look at the unit tests that were failing. 

When I ran all the tests, 9 failed and 37 passed. Prof. Mei mentioned 3 unit tests you were unsure about. I am not sure which ones they are. Should 9 be failing in the first place? Do I have my environment set up incorrectly? 

I took a look at test_basic.py and 3 tests failed in it-

1. test_remove_newline (__main__.TestApplied)

canApply() should return False. I am not really sure what is going on here. I played around with the test case and I can't seem to get it to return anything but True. Looks like I'm missing something? I would have to investigate in more detail to find out.

2. test_remove_offset & test_remove_offset_similar_2

I think there is a small bug in the test case itself? The tool is returning the output we are expecting ("No context related issues found.”) but the `self.assertEqual ` in the test case is not functioning as expected?

**Comment by vikramsubramanian** [comment]
> With regards to #6 above, if GIT apply detects that, for a patch applying to dir/file.c, the actual root is path/dir/file.c (since we're currently sitting inside the path directory), it'll report it's finding against path/dir/file.c. This caused a mismatch where we would look at the patch file, notice no error messages against dir/file.c from GIT, and assume the patch had been applied successfully (since the error message was against path/dir/file.c). The fix is starting at https://github.com/gwurster/ApplyPlus/blob/master/scripts/patch_apply/apply.py#L19, with another comment at https://github.com/gwurster/ApplyPlus/blob/master/scripts/patch_apply/apply.py#L294. The test code for the findGitPrefix function is https://github.com/gwurster/ApplyPlus/blob/master/tests/test_apply.py#L94.
> 
> With regards to #8, https://github.com/gwurster/ApplyPlus/blob/master/scripts/patch_apply/patchParser.py#L62 is the start of the regular expressions that I think you're referring to. The @@....@@ lines for hunk location is described at https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html. The 'from-file-line-numbers' and 'to-file-line-numbers' contain a 'start,count', but the count only exists if there is more than one line. The previous string split call assumed all four numbers always existed and would raise an exception if the count was missing on either the from or to line numbers. A test case which causes a missing count is either patching a file that was originally one line long, or removing from a file so that the end result is a file that is one line long. It appears I missed adding a test case for those situations.

Thank you for the clarification :)

**Pull request merged**
